# Generated by Django 4.0.4 on 2022-05-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='size',
            new_name='size_s',
        ),
    ]
