# Generated by Django 4.0.4 on 2022-05-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_alter_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
