# Generated by Django 4.0.4 on 2022-05-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_alter_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='brand',
            field=models.CharField(db_column='brand_mark', max_length=255, unique=True),
        ),
    ]
