# Generated by Django 4.0.4 on 2022-05-06 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_page_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
