# Generated by Django 4.0.4 on 2022-05-07 16:47

import Store.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_alter_topic_topic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(default=Store.models.default_city, max_length=30, validators=[Store.models.validate_city]),
        ),
        migrations.AlterField(
            model_name='store',
            name='date',
            field=models.DateField(default=datetime.date(2022, 5, 7)),
        ),
        migrations.CreateModel(
            name='EntryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.topictable')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
