# Generated by Django 4.0.4 on 2022-05-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_topictable_alter_store_city_alter_store_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='owner',
            field=models.CharField(default='tiana', max_length=40),
            preserve_default=False,
        ),
    ]
