# Generated by Django 4.0.4 on 2022-05-13 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_topic_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='size_s',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
        migrations.AlterField(
            model_name='store',
            name='date',
            field=models.DateField(default=datetime.date(2022, 5, 13)),
        ),
    ]
