# Generated by Django 4.0.4 on 2022-05-13 19:50

import Store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_person_store_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='family',
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(help_text='add age'),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(default=Store.models.default_city, max_length=50, validators=[Store.models.validate_city]),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
